/*
 * Copyright (c) 2026 Dean Sellers (dean@sellers.id.au)
 * SPDX-License-Identifier: MIT
 *
 * test_tls_integration.cpp - TLS integration tests against a real MQTT broker.
 *
 * These tests are compiled ONLY for native_sim (CONFIG_ETH_NATIVE_TAP=y)
 * AND when CONFIG_MQTT_LIB_TLS is enabled.
 *
 * They exercise an end-to-end TLS handshake using certificates generated by
 * tests/scripts/gen_test_certs.sh and a Mosquitto broker configured by
 * tests/scripts/mosquitto_tls.conf.
 *
 * Setup (one time):
 *   tests/scripts/gen_test_certs.sh
 *
 * Run:
 *   # Build for native_sim with TLS overlay
 *   west build -p always -s sml-mqtt-cli/tests -b native_sim \
 *     -- -DZEPHYR_MODULES="$PWD/boost-sml;$PWD/sml-mqtt-cli" \
 *        -DCONF_FILE="prj.conf;prj_tls.conf"
 *
 *   # Start the TLS broker on the host
 *   mosquitto -c tests/scripts/mosquitto_tls.conf &
 *
 *   # Bring up TAP, load certs, run
 *   sudo tests/scripts/run_integration_tests.sh --tls
 *
 * The Zephyr app gets static IP 192.0.2.2; the host TAP interface is
 * 192.0.2.1; the broker listens on 192.0.2.1:8883.
 *
 * Test certificates:
 *   All three credential entries use the same security tag (TLS_TAG).
 *   - TLS_TAG / CA_CERTIFICATE      -> tests/scripts/certs/ca.crt
 *   - TLS_TAG / SERVER_CERTIFICATE  -> tests/scripts/certs/client.crt
 *   - TLS_TAG / PRIVATE_KEY         -> tests/scripts/certs/client.key
 *
 * The certificates are compiled in via INCBIN macros (see CMakeLists.txt).
 */

#if defined(CONFIG_ETH_NATIVE_TAP) && defined(CONFIG_MQTT_LIB_TLS)

#include <zephyr/ztest.h>
#include <zephyr/kernel.h>
#include <zephyr/logging/log.h>
#include <zephyr/net/mqtt.h>
#include <zephyr/net/net_if.h>
#include <zephyr/net/tls_credentials.h>
#include <zephyr/sys/util.h>
#include <sml-mqtt-cli.hpp>

LOG_MODULE_REGISTER(test_tls_integ, CONFIG_MQTT_LOG_LEVEL);

/* Declared in main.cpp - drives one round of socket I/O. */
extern void client_poll_and_input(sml_mqtt_cli::mqtt_client &client);

/* -------------------------------------------------------------------------
 * Test certificate blobs (compiled in via CMakeLists.txt INCBIN / extern)
 * -------------------------------------------------------------------------
 * The integration test runner (run_integration_tests.sh --tls) sets up a
 * ramfs mount and writes the DER-encoded certificates there.  In native_sim
 * we read them as standard C arrays declared in a generated header.
 *
 * For simplicity, the test certs are embedded as extern const arrays
 * declared in a companion file tls_test_certs.c (generated by CMakeLists
 * from PEM -> C array conversion). The arrays are included here.
 *
 * Fallback: if no cert arrays are available, the tests skip themselves.
 * ------------------------------------------------------------------------- */

/* Security tag shared across all three credential types for this test. */
#define TLS_TAG 42

/* Build-time broker address/port — overrideable like the plaintext tests. */
#ifndef SML_MQTT_TEST_BROKER_HOST
#define SML_MQTT_TEST_BROKER_HOST "192.0.2.1"
#endif

#ifndef SML_MQTT_TEST_TLS_PORT
#define SML_MQTT_TEST_TLS_PORT 8883
#endif

#define INTEG_TLS_TIMEOUT_MS 10000

/* -------------------------------------------------------------------------
 * Test certificate data — declared as weak symbols so the build succeeds
 * even without generated cert headers; the tests skip if the arrays are
 * empty (zero size = no cert generated).
 * ------------------------------------------------------------------------- */

extern const unsigned char sml_test_ca_cert[]     __attribute__((weak));
extern const size_t        sml_test_ca_cert_len    __attribute__((weak));
extern const unsigned char sml_test_client_cert[]  __attribute__((weak));
extern const size_t        sml_test_client_cert_len __attribute__((weak));
extern const unsigned char sml_test_client_key[]   __attribute__((weak));
extern const size_t        sml_test_client_key_len  __attribute__((weak));

static bool certs_available(void)
{
	return (sml_test_ca_cert != NULL && sml_test_ca_cert_len > 0 &&
		sml_test_client_cert != NULL && sml_test_client_cert_len > 0 &&
		sml_test_client_key != NULL && sml_test_client_key_len > 0);
}

/* -------------------------------------------------------------------------
 * Polling helpers (same pattern as test_integration_broker.cpp)
 * ------------------------------------------------------------------------- */

static void poll_loop(sml_mqtt_cli::mqtt_client &client, int duration_ms)
{
	int64_t deadline = k_uptime_get() + duration_ms;

	while (k_uptime_get() < deadline) {
		mqtt_live(&client.get_context().client);
		client_poll_and_input(client);
		k_sleep(K_MSEC(10));
	}
}

static bool wait_for_state(sml_mqtt_cli::mqtt_client &client, const char *state,
			   int timeout_ms = INTEG_TLS_TIMEOUT_MS)
{
	int64_t deadline = k_uptime_get() + timeout_ms;

	while (k_uptime_get() < deadline) {
		mqtt_live(&client.get_context().client);
		client_poll_and_input(client);
		if (strcmp(client.get_state(), state) == 0) {
			return true;
		}
		k_sleep(K_MSEC(10));
	}
	return false;
}

static int g_tls_rx_count;
static char g_tls_rx_topic[CONFIG_SML_MQTT_CLI_MAX_TOPIC_LEN];
static uint8_t g_tls_rx_payload[CONFIG_SML_MQTT_CLI_MAX_PAYLOAD_LEN];
static size_t  g_tls_rx_payload_len;

static void on_tls_message(void *user_data, const char *topic,
			   const uint8_t *payload, size_t len,
			   enum mqtt_qos qos)
{
	ARG_UNUSED(user_data);
	ARG_UNUSED(qos);

	g_tls_rx_count++;
	strncpy(g_tls_rx_topic, topic ? topic : "", sizeof(g_tls_rx_topic) - 1);
	g_tls_rx_topic[sizeof(g_tls_rx_topic) - 1] = '\0';
	g_tls_rx_payload_len = MIN(len, sizeof(g_tls_rx_payload));
	memcpy(g_tls_rx_payload, payload, g_tls_rx_payload_len);
}

static void reset_tls_rx(void)
{
	g_tls_rx_count       = 0;
	g_tls_rx_payload_len = 0;
	memset(g_tls_rx_topic,   0, sizeof(g_tls_rx_topic));
	memset(g_tls_rx_payload, 0, sizeof(g_tls_rx_payload));
}

static bool wait_tls_rx(sml_mqtt_cli::mqtt_client &subscriber, int expected,
			int timeout_ms = INTEG_TLS_TIMEOUT_MS)
{
	int64_t deadline = k_uptime_get() + timeout_ms;

	while (g_tls_rx_count < expected && k_uptime_get() < deadline) {
		mqtt_live(&subscriber.get_context().client);
		client_poll_and_input(subscriber);
		k_sleep(K_MSEC(10));
	}
	return g_tls_rx_count >= expected;
}

/* -------------------------------------------------------------------------
 * Credential registration helper — called once per suite run.
 * ------------------------------------------------------------------------- */

static bool credentials_registered;

static int register_test_credentials(void)
{
	int ret;

	ret = tls_credential_add(TLS_TAG, TLS_CREDENTIAL_CA_CERTIFICATE,
				 sml_test_ca_cert, sml_test_ca_cert_len);
	if (ret < 0 && ret != -EEXIST) {
		LOG_ERR("Failed to add CA cert: %d", ret);
		return ret;
	}

	ret = tls_credential_add(TLS_TAG, TLS_CREDENTIAL_SERVER_CERTIFICATE,
				 sml_test_client_cert, sml_test_client_cert_len);
	if (ret < 0 && ret != -EEXIST) {
		LOG_ERR("Failed to add client cert: %d", ret);
		return ret;
	}

	ret = tls_credential_add(TLS_TAG, TLS_CREDENTIAL_PRIVATE_KEY,
				 sml_test_client_key, sml_test_client_key_len);
	if (ret < 0 && ret != -EEXIST) {
		LOG_ERR("Failed to add client key: %d", ret);
		return ret;
	}

	credentials_registered = true;
	return 0;
}

/* -------------------------------------------------------------------------
 * Per-test connect/disconnect helpers
 * ------------------------------------------------------------------------- */

static void tls_connect(sml_mqtt_cli::mqtt_client &client, const char *id)
{
	static const sec_tag_t tags[] = {TLS_TAG};
	sml_mqtt_cli::tls_config tls = {
		.sec_tag_list  = tags,
		.sec_tag_count = 1,
		.peer_verify   = TLS_PEER_VERIFY_REQUIRED,
	};

	int ret = client.init(id, &tls);
	zassert_equal(ret, 0, "TLS init(%s) failed: %d", id, ret);

	client.set_publish_received_callback(on_tls_message, nullptr);

	ret = client.connect(SML_MQTT_TEST_BROKER_HOST, SML_MQTT_TEST_TLS_PORT,
			     true);
	zassert_equal(ret, 0, "TLS connect failed: %d", ret);

	bool connected = wait_for_state(client, "Connected");
	zassert_true(connected, "Timed out waiting for TLS Connected state");

	LOG_INF("TLS client '%s' connected to %s:%d",
		id, SML_MQTT_TEST_BROKER_HOST, SML_MQTT_TEST_TLS_PORT);
}

static void tls_disconnect(sml_mqtt_cli::mqtt_client &client)
{
	client.disconnect();
	poll_loop(client, 200);
}

/* -------------------------------------------------------------------------
 * Suite setup/teardown
 * ------------------------------------------------------------------------- */

static void *tls_integ_setup(void)
{
	if (!certs_available()) {
		LOG_WRN("Test certificates not compiled in — skipping TLS "
			"integration tests.  Run gen_test_certs.sh first.");
		return NULL;
	}

	int ret = register_test_credentials();

	if (ret < 0) {
		LOG_ERR("Failed to register TLS credentials: %d", ret);
		return NULL;
	}

	return NULL;
}

static void tls_integ_before(void *data)
{
	ARG_UNUSED(data);
	reset_tls_rx();
}

ZTEST_SUITE(sml_mqtt_tls_integration, NULL, tls_integ_setup,
	    tls_integ_before, NULL, NULL);

/* -------------------------------------------------------------------------
 * Tests
 * ------------------------------------------------------------------------- */

/**
 * @brief TLS handshake completes and the SM reaches Connected state.
 */
ZTEST(sml_mqtt_tls_integration, test_tls_connect_disconnect)
{
	if (!certs_available()) {
		ztest_test_skip();
	}

	sml_mqtt_cli::mqtt_client client;
	tls_connect(client, "tls-integ-conn");
	zassert_true(client.is_connected(), "Expected connected after TLS handshake");

	tls_disconnect(client);
	zassert_false(client.is_connected(), "Expected disconnected after TLS disconnect");
}

/**
 * @brief QoS 0 publish succeeds over TLS.
 */
ZTEST(sml_mqtt_tls_integration, test_tls_publish_qos0)
{
	if (!certs_available()) {
		ztest_test_skip();
	}

	sml_mqtt_cli::mqtt_client client;
	tls_connect(client, "tls-integ-pub0");

	int ret = client.subscribe("sml/tls/test", MQTT_QOS_0_AT_MOST_ONCE);
	zassert_equal(ret, 0, "TLS subscribe failed: %d", ret);

	bool subbed = wait_for_state(client, "Connected");
	zassert_true(subbed, "Timed out after TLS subscribe");

	const uint8_t payload[] = "hello-tls-qos0";
	ret = client.publish("sml/tls/test", payload, sizeof(payload) - 1,
			     MQTT_QOS_0_AT_MOST_ONCE);
	zassert_equal(ret, 0, "TLS QoS 0 publish failed: %d", ret);

	bool got_msg = wait_tls_rx(client, 1);
	zassert_true(got_msg, "Did not receive TLS QoS 0 message in time");
	zassert_equal(g_tls_rx_count, 1, "Expected exactly 1 message, got %d",
		      g_tls_rx_count);
	zassert_mem_equal(g_tls_rx_payload, payload, sizeof(payload) - 1,
			  "TLS QoS 0 payload mismatch");

	tls_disconnect(client);
}

/**
 * @brief QoS 1 publish completes (PUBACK received) over TLS.
 */
ZTEST(sml_mqtt_tls_integration, test_tls_publish_qos1)
{
	if (!certs_available()) {
		ztest_test_skip();
	}

	sml_mqtt_cli::mqtt_client client;
	tls_connect(client, "tls-integ-pub1");

	int ret = client.subscribe("sml/tls/qos1", MQTT_QOS_1_AT_LEAST_ONCE);
	zassert_equal(ret, 0, "TLS QoS 1 subscribe failed: %d", ret);
	wait_for_state(client, "Connected");

	const uint8_t payload[] = "hello-tls-qos1";
	ret = client.publish("sml/tls/qos1", payload, sizeof(payload) - 1,
			     MQTT_QOS_1_AT_LEAST_ONCE);
	zassert_equal(ret, 0, "TLS QoS 1 publish failed: %d", ret);

	bool got_msg = wait_tls_rx(client, 1);
	zassert_true(got_msg, "Did not receive TLS QoS 1 message in time");
	zassert_mem_equal(g_tls_rx_payload, payload, sizeof(payload) - 1,
			  "TLS QoS 1 payload mismatch");

	bool connected = wait_for_state(client, "Connected");
	zassert_true(connected, "SM did not return to Connected after QoS 1");

	tls_disconnect(client);
}

/**
 * @brief Verify hostname is copied into context (not a dangling pointer).
 *
 * Constructs the hostname on the stack, calls connect(), then verifies the
 * context holds an independent copy.
 */
ZTEST(sml_mqtt_tls_integration, test_tls_hostname_copied)
{
	if (!certs_available()) {
		ztest_test_skip();
	}

	static const sec_tag_t tags[] = {TLS_TAG};
	sml_mqtt_cli::tls_config tls = {
		.sec_tag_list  = tags,
		.sec_tag_count = 1,
		.peer_verify   = TLS_PEER_VERIFY_REQUIRED,
	};

	sml_mqtt_cli::mqtt_client client;
	int ret = client.init("tls-hostname-copy", &tls);
	zassert_equal(ret, 0, "init failed: %d", ret);

	/* Stack-allocated hostname — would be invalid after this block if
	 * connect() kept a raw pointer rather than copying. */
	{
		char stack_host[] = SML_MQTT_TEST_BROKER_HOST;
		ret = client.connect(stack_host, SML_MQTT_TEST_TLS_PORT, true);
		zassert_equal(ret, 0, "connect failed: %d", ret);
		/* stack_host goes out of scope here */
	}

	/* The SM should still reach Connected with the copied hostname. */
	bool connected = wait_for_state(client, "Connected");
	zassert_true(connected, "TLS connect failed after stack hostname went out of scope");

	/* Verify the context holds an independent copy pointing into ctx. */
	const auto &ctx = client.get_context();
	zassert_equal(ctx.client.transport.tls.config.hostname,
		      ctx.tls_hostname,
		      "hostname pointer must point into ctx.tls_hostname, not caller stack");

	tls_disconnect(client);
}

#endif /* CONFIG_ETH_NATIVE_TAP && CONFIG_MQTT_LIB_TLS */
